// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SensorDataTD

#ifndef _SENSORDATATD_UI_H
#define _SENSORDATATD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_main
void ui_main_screen_init(void);
extern lv_obj_t *ui_main;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_buttonPressed;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_mode;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_gxValue;
extern lv_obj_t *ui_axValue;
extern lv_obj_t *ui_gyValue;
extern lv_obj_t *ui_ayValue;
extern lv_obj_t *ui_gzValue;
extern lv_obj_t *ui_azValue;
extern lv_obj_t *ui_wifiConnected;
extern lv_obj_t *ui_isCallibrated;
// CUSTOM VARIABLES

// SCREEN: ui_pressButton
void ui_pressButton_screen_init(void);
extern lv_obj_t *ui_pressButton;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Label12;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_info_png);   // assets/info.png

// FONTS
LV_FONT_DECLARE( ui_font_bold);
LV_FONT_DECLARE( ui_font_kanit);
LV_FONT_DECLARE( ui_font_boldS);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
