// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SensorDataTD

#include "ui.h"

void ui_main_screen_init(void)
{
ui_main = lv_obj_create(NULL);
lv_obj_clear_flag( ui_main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_main);
lv_img_set_src(ui_Image2, &ui_img_info_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 170
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_main);
lv_obj_set_width( ui_Panel1, 50);
lv_obj_set_height( ui_Panel1, 50);
lv_obj_set_x( ui_Panel1, -117 );
lv_obj_set_y( ui_Panel1, 44 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x333547), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_main);
lv_obj_set_width( ui_Panel2, 50);
lv_obj_set_height( ui_Panel2, 50);
lv_obj_set_x( ui_Panel2, -64 );
lv_obj_set_y( ui_Panel2, 44 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x333547), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_main);
lv_obj_set_width( ui_Panel3, 50);
lv_obj_set_height( ui_Panel3, 50);
lv_obj_set_x( ui_Panel3, -11 );
lv_obj_set_y( ui_Panel3, 44 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x333547), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonPressed = lv_obj_create(ui_main);
lv_obj_set_width( ui_buttonPressed, 107);
lv_obj_set_height( ui_buttonPressed, 50);
lv_obj_set_x( ui_buttonPressed, 70 );
lv_obj_set_y( ui_buttonPressed, 44 );
lv_obj_set_align( ui_buttonPressed, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_buttonPressed, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_buttonPressed, lv_color_hex(0x333547), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_buttonPressed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_buttonPressed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_main);
lv_obj_set_width( ui_Panel4, 265);
lv_obj_set_height( ui_Panel4, 26);
lv_obj_set_x( ui_Panel4, -9 );
lv_obj_set_y( ui_Panel4, 3 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x333547), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -133 );
lv_obj_set_y( ui_Label1, 55 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"AX");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_kanit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -79 );
lv_obj_set_y( ui_Label2, 55 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"AY");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &ui_font_kanit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -80 );
lv_obj_set_y( ui_Label3, 34 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"GY");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &ui_font_kanit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -127 );
lv_obj_set_y( ui_Label4, 5 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Wifi:");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &ui_font_kanit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mode = lv_label_create(ui_main);
lv_obj_set_width( ui_mode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mode, 98 );
lv_obj_set_y( ui_mode, 5 );
lv_obj_set_align( ui_mode, LV_ALIGN_CENTER );
lv_label_set_text(ui_mode,"MODE A");
lv_obj_set_style_text_color(ui_mode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mode, &ui_font_kanit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 44 );
lv_obj_set_y( ui_Label6, -27 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"+Motion Capture");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &ui_font_bold, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 40 );
lv_obj_set_y( ui_Label7, 60 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"BUTTON");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &ui_font_kanit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -73 );
lv_obj_set_y( ui_Label8, 5 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Calibration:");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &ui_font_kanit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -133 );
lv_obj_set_y( ui_Label9, 34 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"GX");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &ui_font_kanit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -27 );
lv_obj_set_y( ui_Label10, 55 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"AZ");
lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label10, &ui_font_kanit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -27 );
lv_obj_set_y( ui_Label11, 34 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"GZ");
lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &ui_font_kanit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gxValue = lv_label_create(ui_main);
lv_obj_set_width( ui_gxValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gxValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_gxValue, -109 );
lv_obj_set_y( ui_gxValue, 33 );
lv_obj_set_align( ui_gxValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_gxValue,"0.5");
lv_obj_set_style_text_color(ui_gxValue, lv_color_hex(0xC2C8FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_gxValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_gxValue, &ui_font_boldS, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_axValue = lv_label_create(ui_main);
lv_obj_set_width( ui_axValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_axValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_axValue, -109 );
lv_obj_set_y( ui_axValue, 54 );
lv_obj_set_align( ui_axValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_axValue,"0.5");
lv_obj_set_style_text_color(ui_axValue, lv_color_hex(0xC2C8FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_axValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_axValue, &ui_font_boldS, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gyValue = lv_label_create(ui_main);
lv_obj_set_width( ui_gyValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gyValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_gyValue, -56 );
lv_obj_set_y( ui_gyValue, 33 );
lv_obj_set_align( ui_gyValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_gyValue,"0.5");
lv_obj_set_style_text_color(ui_gyValue, lv_color_hex(0xC2C8FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_gyValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_gyValue, &ui_font_boldS, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ayValue = lv_label_create(ui_main);
lv_obj_set_width( ui_ayValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ayValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ayValue, -56 );
lv_obj_set_y( ui_ayValue, 54 );
lv_obj_set_align( ui_ayValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_ayValue,"0.5");
lv_obj_set_style_text_color(ui_ayValue, lv_color_hex(0xC2C8FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ayValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ayValue, &ui_font_boldS, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gzValue = lv_label_create(ui_main);
lv_obj_set_width( ui_gzValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gzValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_gzValue, -2 );
lv_obj_set_y( ui_gzValue, 33 );
lv_obj_set_align( ui_gzValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_gzValue,"0.5");
lv_obj_set_style_text_color(ui_gzValue, lv_color_hex(0xC2C8FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_gzValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_gzValue, &ui_font_boldS, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_azValue = lv_label_create(ui_main);
lv_obj_set_width( ui_azValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_azValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_azValue, -3 );
lv_obj_set_y( ui_azValue, 54 );
lv_obj_set_align( ui_azValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_azValue,"0.5");
lv_obj_set_style_text_color(ui_azValue, lv_color_hex(0xC2C8FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_azValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_azValue, &ui_font_boldS, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiConnected = lv_obj_create(ui_main);
lv_obj_set_width( ui_wifiConnected, 7);
lv_obj_set_height( ui_wifiConnected, 7);
lv_obj_set_x( ui_wifiConnected, -36 );
lv_obj_set_y( ui_wifiConnected, 4 );
lv_obj_set_align( ui_wifiConnected, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_wifiConnected, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wifiConnected, lv_color_hex(0x147D00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifiConnected, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_wifiConnected, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_isCallibrated = lv_obj_create(ui_main);
lv_obj_set_width( ui_isCallibrated, 7);
lv_obj_set_height( ui_isCallibrated, 7);
lv_obj_set_x( ui_isCallibrated, -110 );
lv_obj_set_y( ui_isCallibrated, 4 );
lv_obj_set_align( ui_isCallibrated, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_isCallibrated, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_isCallibrated, lv_color_hex(0x147D00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_isCallibrated, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_isCallibrated, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



}
